# Generated by Django 5.1.2 on 2025-10-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skill_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
