# Generated by Django 5.1.2 on 2025-10-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_exchangerequest_receiver_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='skill_photos/'),
        ),
    ]
