# Generated by Django 5.1.2 on 2025-10-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_skill_description_skill_experience_years_skill_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=20),
        ),
    ]
