# Generated by Django 5.1.2 on 2025-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skills_can_teach',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='accounts.skill'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills_to_learn',
            field=models.ManyToManyField(blank=True, related_name='learners', to='accounts.skill'),
        ),
    ]
