# Generated by Django 5.1.2 on 2025-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_exchangerequest_message_exchangerequest_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='receiver_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='sender_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points_hold',
            field=models.IntegerField(default=0),
        ),
    ]
